### ISSUE TITLE
libsourcey build fails on Mac OSX 10.10 GCC 6.3

### ISSUE THREAD

**Issue by carlosb** [sourcey/libsourcey#177]
As title indicates, `libsourcey` fails to build on OSX 10.10. In particular, when building `avfoundation.mm.o` one is presented with the error output:

````
Building CXX object av/CMakeFiles/av.dir/src/apple/avfoundation.mm.o
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:0,
                 from /System/Library/Frameworks/AVFoundation.framework/Headers/AVAudioTypes.h:11,
                 from /System/Library/Frameworks/AVFoundation.framework/Headers/AVAudioBuffer.h:8,
                 from /System/Library/Frameworks/AVFoundation.framework/Headers/AVFoundation.h:14,
                 from /Users/carlos/Packages/libsourcey/libsourcey/src/av/src/apple/avfoundation.mm:10:
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:59:42: error: expected ')' before '(' token
 - (void)enumerateObjectsUsingBlock:(void (^)(id obj, NSUInteger idx, BOOL *stop))block NS_AVAILABLE(10_6, 4_0);
                                          ^
...

make[2]: *** [av/CMakeFiles/av.dir/build.make:63: av/CMakeFiles/av.dir/src/apple/avfoundation.mm.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:571: av/CMakeFiles/av.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

````
You can read the whole output in the file [log.txt](https://github.com/sourcey/libsourcey/files/1216889/log.txt).

I am using GCC 6.3 and CMake 3.8.2. The syntax appears to be Objective-C syntax which means that GCC can't parse it, therefore throwing a syntax error.

So I tried setting the following CMake flags in various different combinations to no avail (To confirm, I tried them all at once):
````
-DAVFOUNDATION=AVFOUNDATION-NOTFOUND
-DBUILD_MODULE_av=OFF
-DBUILD_SAMPLES_av=OFF
-DBUILD_TESTS_av=OFF
````

I will update if I find a workaround fix.

**Comment by carlosb** [comment]
Okay I'm stupid, I should have confirmed it better but I just had this realization. CMake was choosing `gcc` for the C Compiler and `g++` for the C++ Compiler when it should have been choosing `clang` for the C Compiler and `g++` for the C++ Compiler. Changing it to `clang` did the trick.

However just for the sake of making noise I'm getting the warning and error from #169 and from #135. So it means I still haven't got it to build.
````
ld: warning: directory not found for option '-L/usr/local/share/libsourcey/vendor/lib'
ld: warning: directory not found for option '-L/usr/local/share/libsourcey/vendor/lib'
Undefined symbols for architecture x86_64:
  "scy::av::avfoundation::getDeviceList(scy::av::Device::Type, std::vector<scy::av::Device, std::allocator<scy::av::Device> >&)", referenced from:
      scy::av::DeviceManager::getDeviceList(scy::av::Device::Type, std::vector<scy::av::Device, std::allocator<scy::av::Device> >&) in devicemanager.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [av/CMakeFiles/av.dir/build.make:638: av/libscy_av.1.0.2.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:571: av/CMakeFiles/av.dir/all] Error 2
````

Please close.

**Comment by auscaster** [comment]
Hey, that may be because the scy::av::avfoundation::getDeviceList is not
included in your build due to the custom flags you are passing. I think you
need to find a way to include avfoundation.mm or comment the reference out
from the DeviceManager

**Comment by carlosb** [comment]
So just to update, I actually ended up switching from GCC to AppleClang 8.x (Apple's default compiler) and everything worked like a charm. Such a shame that using GCC on Mac is such a hassle.

**Comment by auscaster** [comment]
Yep thats a bummer. I'm playing with my mac a bit this week and will run
some tests and follow up here
